export const FOOD_ITEMS_SEED = [
  { name: 'Rice', category: 'grain', expirationDays: 180, costPerUnit: 50 },
  {
    name: 'Wheat Flour',
    category: 'grain',
    expirationDays: 120,
    costPerUnit: 45,
  },
  { name: 'Milk', category: 'dairy', expirationDays: 3, costPerUnit: 70 },
  { name: 'Eggs', category: 'dairy', expirationDays: 14, costPerUnit: 12 },
  {
    name: 'Chicken Breast',
    category: 'protein',
    expirationDays: 3,
    costPerUnit: 180,
  },
  { name: 'Fish', category: 'protein', expirationDays: 2, costPerUnit: 250 },
  {
    name: 'Potato',
    category: 'vegetable',
    expirationDays: 30,
    costPerUnit: 25,
  },
  { name: 'Onion', category: 'vegetable', expirationDays: 25, costPerUnit: 35 },
  {
    name: 'Garlic',
    category: 'vegetable',
    expirationDays: 60,
    costPerUnit: 90,
  },
  { name: 'Apple', category: 'fruit', expirationDays: 10, costPerUnit: 20 },
  { name: 'Banana', category: 'fruit', expirationDays: 5, costPerUnit: 10 },
  { name: 'Tomato', category: 'vegetable', expirationDays: 7, costPerUnit: 40 },
  {
    name: 'Carrot',
    category: 'vegetable',
    expirationDays: 20,
    costPerUnit: 30,
  },
  { name: 'Bread', category: 'grain', expirationDays: 5, costPerUnit: 35 },
  { name: 'Cheese', category: 'dairy', expirationDays: 15, costPerUnit: 120 },
  { name: 'Yogurt', category: 'dairy', expirationDays: 10, costPerUnit: 50 },
  {
    name: 'Lentils',
    category: 'protein',
    expirationDays: 365,
    costPerUnit: 110,
  },
  { name: 'Beans', category: 'protein', expirationDays: 365, costPerUnit: 120 },
  { name: 'Oil', category: 'cooking', expirationDays: 365, costPerUnit: 150 },
  { name: 'Salt', category: 'cooking', expirationDays: 1000, costPerUnit: 30 },
];
