export const RESOURCES_SEED = [
  {
    title: 'How to Store Vegetables Properly',
    description: 'Learn the correct way to store vegetables to reduce waste.',
    url: 'https://example.com/storage/veg',
    category: 'storage',
    type: 'article',
  },
  {
    title: 'Low Budget Meal Planning',
    description: 'Simple food planning ideas for low budget families.',
    url: 'https://example.com/budget/meals',
    category: 'budget',
    type: 'video',
  },
  {
    title: 'Avoid Food Waste with Smart Habits',
    description: 'Easy habits to reduce waste.',
    url: 'https://example.com/waste/smart',
    category: 'waste-reduction',
    type: 'article',
  },
  {
    title: 'Nutrition Basics for Daily Meals',
    description: 'Essential nutrition guide.',
    url: 'https://example.com/nutrition/basics',
    category: 'nutrition',
    type: 'guide',
  },
  {
    title: 'Proper Fruit Storage Tips',
    description: 'Learn how to store fruits long-term.',
    url: 'https://example.com/storage/fruits',
    category: 'storage',
    type: 'article',
  },
  {
    title: 'How to Freeze Foods for Weeks',
    description: 'Everything you need to know about freezing foods.',
    url: 'https://example.com/freezing/foods',
    category: 'storage',
    type: 'video',
  },
  {
    title: 'Healthy Eating on a Budget',
    description: 'Nutrition + budget combination tips.',
    url: 'https://example.com/budget/health',
    category: 'budget',
    type: 'guide',
  },
  {
    title: 'Avoid Spices Getting Rotten',
    description: 'Correct way to store spices.',
    url: 'https://example.com/spices/store',
    category: 'storage',
    type: 'article',
  },
  {
    title: 'Food Waste Awareness',
    description: 'Why food waste is harmful.',
    url: 'https://example.com/waste/awareness',
    category: 'waste-reduction',
    type: 'video',
  },
  {
    title: '3-Day Meal Plan',
    description: 'Simple meal planning system.',
    url: 'https://example.com/meal/plan',
    category: 'nutrition',
    type: 'guide',
  },
  {
    title: 'Store Dairy Items Correctly',
    description: 'Prevent milk & cheese from spoiling.',
    url: 'https://example.com/storage/dairy',
    category: 'storage',
    type: 'article',
  },
  {
    title: 'Kitchen Organization Tips',
    description: 'Organize your kitchen to reduce waste.',
    url: 'https://example.com/kitchen/organization',
    category: 'waste-reduction',
    type: 'guide',
  },
  {
    title: 'Save Money Cooking at Home',
    description: 'Reduce food cost easily.',
    url: 'https://example.com/budget/homecooking',
    category: 'budget',
    type: 'video',
  },
  {
    title: 'Smart Refrigerator Tips',
    description: 'Use your fridge efficiently.',
    url: 'https://example.com/storage/fridge',
    category: 'storage',
    type: 'article',
  },
  {
    title: 'Vegetarian Nutrition Basics',
    description: 'Nutrients needed for veg diets.',
    url: 'https://example.com/nutrition/veg',
    category: 'nutrition',
    type: 'guide',
  },
  {
    title: 'Reduce Grocery Waste',
    description: 'Buy only what you need.',
    url: 'https://example.com/waste/grocery',
    category: 'waste-reduction',
    type: 'article',
  },
  {
    title: 'Budget-Friendly Shopping List',
    description: 'Affordable weekly shopping ideas.',
    url: 'https://example.com/budget/list',
    category: 'budget',
    type: 'guide',
  },
  {
    title: 'Safe Food Storage Temperatures',
    description: 'What temps keep food fresh longest.',
    url: 'https://example.com/storage/temp',
    category: 'storage',
    type: 'video',
  },
  {
    title: 'Nutrition for Families',
    description: 'Meal nutrition guide for kids & adults.',
    url: 'https://example.com/nutrition/family',
    category: 'nutrition',
    type: 'article',
  },
  {
    title: 'Zero-Waste Kitchen',
    description: 'Beginner guide to a zero-waste lifestyle.',
    url: 'https://example.com/waste/zero',
    category: 'waste-reduction',
    type: 'guide',
  },
];
